### ISSUE TITLE
PdfFeatures extractor error

### ISSUE THREAD

**Issue by mllife** [huridocs/pdf-reading-order#1]
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdftohtml'

**Comment by mllife** [comment]
was able to fix the issue, it was due to "Poppler" library

**Comment by gabriel-piles** [comment]
I apologize for the delayed response. 

I'm glad you solved it! 

Have a great day.
